//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMQClient.MSMQServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MSMQServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/SendLockMessage")]
        void SendLockMessage(string msg, System.DateTime sendDate);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/SendLockMessage")]
        System.Threading.Tasks.Task SendLockMessageAsync(string msg, System.DateTime sendDate);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/SendToOutputWindow")]
        void SendToOutputWindow(string msg, System.DateTime sendDate);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/SendToOutputWindow")]
        System.Threading.Tasks.Task SendToOutputWindowAsync(string msg, System.DateTime sendDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MSMQClient.MSMQServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MSMQClient.MSMQServiceReference.IService1>, MSMQClient.MSMQServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendLockMessage(string msg, System.DateTime sendDate) {
            base.Channel.SendLockMessage(msg, sendDate);
        }
        
        public System.Threading.Tasks.Task SendLockMessageAsync(string msg, System.DateTime sendDate) {
            return base.Channel.SendLockMessageAsync(msg, sendDate);
        }
        
        public void SendToOutputWindow(string msg, System.DateTime sendDate) {
            base.Channel.SendToOutputWindow(msg, sendDate);
        }
        
        public System.Threading.Tasks.Task SendToOutputWindowAsync(string msg, System.DateTime sendDate) {
            return base.Channel.SendToOutputWindowAsync(msg, sendDate);
        }
    }
}
